// Augments the `CloudflareEnv` interface generated by `wrangler types`
// (cloudflare-env.d.ts, regenerated by `npm run cf-typegen`) with the
// secret-backed vars that don't appear in wrangler.jsonc: DATABASE_URL and
// DATABASE_AUTH_TOKEN are set via `wrangler secret put` in production and
// `.dev.vars` locally, so static config alone can't tell wrangler about
// them.
interface CloudflareEnv {
  DATABASE_URL?: string;
  DATABASE_AUTH_TOKEN?: string;
}
